SELECT
    wiki_db,
    DATE(CONCAT(LEFT(registration_approx, 6), "01")) AS registration_month,
    registration_type,
    SUM(day_revisions >= 1 AND revisions_month_1 >= 1) AS trial_1_survival_1,
    SUM(day_revisions >= 1 AND revisions_month_2 >= 1) AS trial_2_survival_1,
    SUM(day_revisions >= 1 AND revisions_month_3 >= 1) AS trial_3_survival_1,
    SUM(day_revisions >= 1 AND revisions_month_4 >= 1) AS trial_4_survival_1,
    SUM(day_revisions >= 1 AND revisions_month_5 >= 1) AS trial_5_survival_1,
    SUM(day_revisions >= 1 AND revisions_month_6 >= 1) AS trial_6_survival_1,
    SUM(day_revisions >= 1 AND revisions_month_1+revisions_month_2 >= 1) AS trial_1_survival_2,
    SUM(day_revisions >= 1 AND revisions_month_2+revisions_month_3 >= 1) AS trial_2_survival_2,
    SUM(day_revisions >= 1 AND revisions_month_3+revisions_month_4 >= 1) AS trial_3_survival_2,
    SUM(day_revisions >= 1 AND revisions_month_4+revisions_month_5 >= 1) AS trial_4_survival_2,
    SUM(day_revisions >= 1 AND revisions_month_5+revisions_month_6 >= 1) AS trial_5_survival_2,
    SUM(day_revisions >= 1 AND revisions_month_6+revisions_month_7 >= 1) AS trial_6_survival_2,
    SUM(day_revisions >= 1 AND revisions_month_1+revisions_month_2+revisions_month_3 >= 1) AS trial_1_survival_3,
    SUM(day_revisions >= 1 AND revisions_month_2+revisions_month_3+revisions_month_4 >= 1) AS trial_2_survival_3,
    SUM(day_revisions >= 1 AND revisions_month_3+revisions_month_4+revisions_month_5 >= 1) AS trial_3_survival_3,
    SUM(day_revisions >= 1 AND revisions_month_4+revisions_month_5+revisions_month_6 >= 1) AS trial_4_survival_3,
    SUM(day_revisions >= 1 AND revisions_month_5+revisions_month_6+revisions_month_7 >= 1) AS trial_5_survival_3,
    SUM(day_revisions >= 1 AND revisions_month_6+revisions_month_7+revisions_month_8 >= 1) AS trial_6_survival_3,
    SUM(day_revisions >= 1 AND revisions_month_1+revisions_month_2+revisions_month_3+revisions_month_4 >= 1) AS trial_1_survival_4,
    SUM(day_revisions >= 1 AND revisions_month_2+revisions_month_3+revisions_month_4+revisions_month_5 >= 1) AS trial_2_survival_4,
    SUM(day_revisions >= 1 AND revisions_month_3+revisions_month_4+revisions_month_5+revisions_month_6 >= 1) AS trial_3_survival_4,
    SUM(day_revisions >= 1 AND revisions_month_4+revisions_month_5+revisions_month_6+revisions_month_7 >= 1) AS trial_4_survival_4,
    SUM(day_revisions >= 1 AND revisions_month_5+revisions_month_6+revisions_month_7+revisions_month_8 >= 1) AS trial_5_survival_4,
    SUM(day_revisions >= 1 AND revisions_month_6+revisions_month_7+revisions_month_8+revisions_month_9 >= 1) AS trial_6_survival_4,
    SUM(day_revisions >= 1 AND revisions_month_1+revisions_month_2+revisions_month_3+revisions_month_4+revisions_month_5 >= 1) AS trial_1_survival_5,
    SUM(day_revisions >= 1 AND revisions_month_2+revisions_month_3+revisions_month_4+revisions_month_5+revisions_month_6 >= 1) AS trial_2_survival_5,
    SUM(day_revisions >= 1 AND revisions_month_3+revisions_month_4+revisions_month_5+revisions_month_6+revisions_month_7 >= 1) AS trial_3_survival_5,
    SUM(day_revisions >= 1 AND revisions_month_4+revisions_month_5+revisions_month_6+revisions_month_7+revisions_month_8 >= 1) AS trial_4_survival_5,
    SUM(day_revisions >= 1 AND revisions_month_5+revisions_month_6+revisions_month_7+revisions_month_8+revisions_month_9 >= 1) AS trial_5_survival_5,
    SUM(day_revisions >= 1 AND revisions_month_6+revisions_month_7+revisions_month_8+revisions_month_9+revisions_month_10 >= 1) AS trial_6_survival_5,
    SUM(day_revisions >= 1 AND revisions_month_1+revisions_month_2+revisions_month_3+revisions_month_4+revisions_month_5+revisions_month_6 >= 1) AS trial_1_survival_6,
    SUM(day_revisions >= 1 AND revisions_month_2+revisions_month_3+revisions_month_4+revisions_month_5+revisions_month_6+revisions_month_7 >= 1) AS trial_2_survival_6,
    SUM(day_revisions >= 1 AND revisions_month_3+revisions_month_4+revisions_month_5+revisions_month_6+revisions_month_7+revisions_month_8 >= 1) AS trial_3_survival_6,
    SUM(day_revisions >= 1 AND revisions_month_4+revisions_month_5+revisions_month_6+revisions_month_7+revisions_month_8+revisions_month_9 >= 1) AS trial_4_survival_6,
    SUM(day_revisions >= 1 AND revisions_month_5+revisions_month_6+revisions_month_7+revisions_month_8+revisions_month_9+revisions_month_10 >= 1) AS trial_5_survival_6,
    SUM(day_revisions >= 1 AND revisions_month_6+revisions_month_7+revisions_month_8+revisions_month_9+revisions_month_10+revisions_month_11 >= 1) AS trial_6_survival_6,
    SUM(day_revisions >= 1 AND revisions_year_1 > 0) AS trial_12_survival_12,
    SUM(day_revisions >= 1 AND revisions_year_2 > 0) AS trial_24_survival_48
FROM new_user_info
LEFT JOIN user_activity_months USING (wiki_db, user_id)
LEFT JOIN new_user_revisions USING (wiki_db, user_id)
GROUP BY 1,2,3;
